---
version: "2.3"
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true
    user: root
    restart: on-failure
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - './jenkins/jenkins_home:/var/jenkins_home'
    dns:
      - 8.8.8.8
      - 4.4.4.4
